version: '3.9'
services:
  database:
    build: ./database/
    ports:
      - '5432:5432'
    volumes:
      - ~/volumes/gunpla_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=foobar
      - POSTGRES_DB=gunpla_db

